Added test file

diff --git a/.github/workflows/zap_api_scan.yml b/.github/workflows/zap_api_scan.yml
--- a/.github/workflows/zap_api_scan.yml
+++ b/.github/workflows/zap_api_scan.yml
@@ -1,52 +1,52 @@
-name: OWASP ZAP API Scan
-
-on: [push]
-
-jobs:
-  zap_scan:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v2
-
-      - name: Pull OWASP ZAP Docker Image
-        run: docker pull zaproxy/zap-stable
-
-      - name: Set permissions for working directory
-        run: |
-             chmod -R 777 $(pwd)
-             mkdir -p $(pwd)/reports
-
-      - name: Clean up existing report
-        run: rm -f zap-report/*.html
-
-      - name: Run ZAP Scan Using OpenAPI Spec
-        run:   |
-          docker run -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap-api-scan.py \
-          -t https://app.qa.az.memcrypt.io  -f openapi \
-          -r zap-report.html || true
-        
-          docker run -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap-api-scan.py \
-          -t https://api.qa.az.memcrypt.io/console/openapi.json -f openapi \
-          -r zap-report-api.html || true
-                  
-          docker run -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap-api-scan.py \
-          -t https://api.qa.az.memcrypt.io/agentbinary/openapi.json -f openapi \
-          -r zap-report-agentbinary.html || true
-
-      - name: Move ZAP reports to reports directory
-        run: mv zap-report*.html reports/    
-          
-      - name: List files in working directory
-        run: ls -la reports
-
-      - name: Upload All ZAP Reports
-        uses: actions/upload-artifact@v4
-        with:
-           name: ZAP Reports
-           path: reports/
-           if-no-files-found: warn
-           compression-level: 6
-           overwrite: false
-           include-hidden-files: false
+#name: OWASP ZAP API Scan
+#
+#on: [push]
+#
+#jobs:
+#  zap_scan:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout Code
+#        uses: actions/checkout@v2
+#
+#      - name: Pull OWASP ZAP Docker Image
+#        run: docker pull zaproxy/zap-stable
+#
+#      - name: Set permissions for working directory
+#        run: |
+#             chmod -R 777 $(pwd)
+#             mkdir -p $(pwd)/reports
+#
+#      - name: Clean up existing report
+#        run: rm -f zap-report/*.html
+#
+#      - name: Run ZAP Scan Using OpenAPI Spec
+#        run:   |
+#          docker run -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap-api-scan.py \
+#          -t https://app.qa.az.memcrypt.io  -f openapi \
+#          -r zap-report.html || true
+#
+#          docker run -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap-api-scan.py \
+#          -t https://api.qa.az.memcrypt.io/console/openapi.json -f openapi \
+#          -r zap-report-api.html || true
+#
+#          docker run -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap-api-scan.py \
+#          -t https://api.qa.az.memcrypt.io/agentbinary/openapi.json -f openapi \
+#          -r zap-report-agentbinary.html || true
+#
+#      - name: Move ZAP reports to reports directory
+#        run: mv zap-report*.html reports/
+#
+#      - name: List files in working directory
+#        run: ls -la reports
+#
+#      - name: Upload All ZAP Reports
+#        uses: actions/upload-artifact@v4
+#        with:
+#           name: ZAP Reports
+#           path: reports/
+#           if-no-files-found: warn
+#           compression-level: 6
+#           overwrite: false
+#           include-hidden-files: false
diff --git a/.github/workflows/zap_scan_list.yml b/.github/workflows/zap_scan_list.yml
--- a/.github/workflows/zap_scan_list.yml
+++ b/.github/workflows/zap_scan_list.yml
@@ -1,89 +1,89 @@
-name: OWASP ZAP Scan from the list
-
-on: [push]
-
-jobs:
-  zap_scan:
-    runs-on: ubuntu-latest
-    env:
-      ENVIRONMENT: qa 
-
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v2
-
-      - name: Pull OWASP ZAP Docker Image
-        run: docker pull zaproxy/zap-stable
-
-      - name: Set permissions for working directory
-        run: |
-             chmod -R 777 $(pwd)
-             mkdir -p $(pwd)/reports
-
-      - name: Clean up existing reports
-        run: rm -f zap-report*.html
-
-      - name: Run ZAP Scans for URLs in File
-        run: |
-         if [[ "$ENVIRONMENT" == "qa" ]]; then
-            URL_FILE="security/zap_url_qa.txt"
-          elif [[ "$ENVIRONMENT" == "sandbox" ]]; then
-            URL_FILE="security/zap_url_sandbox.txt"
-          else
-            echo "Invalid environment specified: $ENVIRONMENT"
-            exit 1
-          fi
-          
-         while IFS= read -r url; do
-          if [[ "$url" == *".json" ]]; then
-            format="openapi"
-          elif [[ "$url" == *"graphql"* ]]; then
-            format="graphql"
-          else
-          format="soap"  
-          fi
-    
-          echo "Scanning $url with inferred format $format"
-          docker run -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap-api-scan.py \
-          -t $url \
-          -f $format \
-          -r "zap-report-$(echo $url | sed 's/[:/.]/-/g').html" \
-          -x "zap-report-$(echo $url | sed 's/[:/.]/-/g').json" || true
-          done < "$URL_FILE"
-
-      - name: Check for Critical Alerts
-        run: |
-         for HTML_REPORT in zap-report-*.html; do
-         if [ -f "$HTML_REPORT" ]; then
-         echo "Processing report: $HTML_REPORT"
-    
-         HIGH_ALERTS=$(grep -o "High" "$HTML_REPORT" | wc -l)
-
-          if [ "$HIGH_ALERTS" -gt 0 ]; then
-            echo "High alerts found in $HTML_REPORT!"
-            echo "Listing the alerts:"
-            
-            grep -A 10 "High" "$HTML_REPORT" 
-          else
-            echo "No high alerts found in $HTML_REPORT."
-          fi
-         else
-            echo "HTML report $HTML_REPORT not found!"
-          fi
-         done
-          
-      - name: Move ZAP reports to reports directory
-        run: mv zap-report*.html reports/
-
-      - name: List files in reports directory
-        run: ls -la reports
-
-      - name: Upload All ZAP Reports
-        uses: actions/upload-artifact@v4
-        with:
-           name: ZAP Reports
-           path: reports/
-           if-no-files-found: warn
-           compression-level: 6
-           overwrite: false
-           include-hidden-files: false
+#name: OWASP ZAP Scan from the list
+#
+#on: [push]
+#
+#jobs:
+#  zap_scan:
+#    runs-on: ubuntu-latest
+#    env:
+#      ENVIRONMENT: qa
+#
+#    steps:
+#      - name: Checkout Code
+#        uses: actions/checkout@v2
+#
+#      - name: Pull OWASP ZAP Docker Image
+#        run: docker pull zaproxy/zap-stable
+#
+#      - name: Set permissions for working directory
+#        run: |
+#             chmod -R 777 $(pwd)
+#             mkdir -p $(pwd)/reports
+#
+#      - name: Clean up existing reports
+#        run: rm -f zap-report*.html
+#
+#      - name: Run ZAP Scans for URLs in File
+#        run: |
+#         if [[ "$ENVIRONMENT" == "qa" ]]; then
+#            URL_FILE="security/zap_url_qa.txt"
+#          elif [[ "$ENVIRONMENT" == "sandbox" ]]; then
+#            URL_FILE="security/zap_url_sandbox.txt"
+#          else
+#            echo "Invalid environment specified: $ENVIRONMENT"
+#            exit 1
+#          fi
+#
+#         while IFS= read -r url; do
+#          if [[ "$url" == *".json" ]]; then
+#            format="openapi"
+#          elif [[ "$url" == *"graphql"* ]]; then
+#            format="graphql"
+#          else
+#          format="soap"
+#          fi
+#
+#          echo "Scanning $url with inferred format $format"
+#          docker run -v $(pwd):/zap/wrk/:rw zaproxy/zap-stable zap-api-scan.py \
+#          -t $url \
+#          -f $format \
+#          -r "zap-report-$(echo $url | sed 's/[:/.]/-/g').html" \
+#          -x "zap-report-$(echo $url | sed 's/[:/.]/-/g').json" || true
+#          done < "$URL_FILE"
+#
+#      - name: Check for Critical Alerts
+#        run: |
+#         for HTML_REPORT in zap-report-*.html; do
+#         if [ -f "$HTML_REPORT" ]; then
+#         echo "Processing report: $HTML_REPORT"
+#
+#         HIGH_ALERTS=$(grep -o "High" "$HTML_REPORT" | wc -l)
+#
+#          if [ "$HIGH_ALERTS" -gt 0 ]; then
+#            echo "High alerts found in $HTML_REPORT!"
+#            echo "Listing the alerts:"
+#
+#            grep -A 10 "High" "$HTML_REPORT"
+#          else
+#            echo "No high alerts found in $HTML_REPORT."
+#          fi
+#         else
+#            echo "HTML report $HTML_REPORT not found!"
+#          fi
+#         done
+#
+#      - name: Move ZAP reports to reports directory
+#        run: mv zap-report*.html reports/
+#
+#      - name: List files in reports directory
+#        run: ls -la reports
+#
+#      - name: Upload All ZAP Reports
+#        uses: actions/upload-artifact@v4
+#        with:
+#           name: ZAP Reports
+#           path: reports/
+#           if-no-files-found: warn
+#           compression-level: 6
+#           overwrite: false
+#           include-hidden-files: false
