Update zap_scan_list.yml

diff --git a/.github/workflows/zap_scan_list.yml b/.github/workflows/zap_scan_list.yml
--- a/.github/workflows/zap_scan_list.yml
+++ b/.github/workflows/zap_scan_list.yml
@@ -5,6 +5,8 @@ on: [push]
 jobs:
   zap_scan:
     runs-on: ubuntu-latest
+    env:
+      ENVIRONMENT: qa 
 
     steps:
       - name: Checkout Code
@@ -23,13 +25,22 @@ jobs:
 
       - name: Run ZAP Scans for URLs in File
         run: |
+         if [[ "$ENVIRONMENT" == "qa" ]]; then
+            URL_FILE="security/zap_urls_qa.txt"
+          elif [[ "$ENVIRONMENT" == "sandbox" ]]; then
+            URL_FILE="security/zap_urls_sandbox.txt"
+          else
+            echo "Invalid environment specified: $ENVIRONMENT"
+            exit 1
+          fi
+          
          while IFS= read -r url; do
           if [[ "$url" == *".json" ]]; then
             format="openapi"
           elif [[ "$url" == *"graphql"* ]]; then
             format="graphql"
           else
-          format="soap"  # Default to SOAP if neither condition matches
+          format="soap"  
           fi
     
           echo "Scanning $url with inferred format $format"
@@ -37,7 +48,7 @@ jobs:
           -t $url \
           -f $format \
           -r "zap-report-$(echo $url | sed 's/[:/.]/-/g').html" || true
-          done < zap_urls.txt
+          done < "$URL_FILE"
 
       - name: Move ZAP reports to reports directory
         run: mv zap-report*.html reports/
