Update zap_scan_list.yml

diff --git a/.github/workflows/zap_scan_list.yml b/.github/workflows/zap_scan_list.yml
--- a/.github/workflows/zap_scan_list.yml
+++ b/.github/workflows/zap_scan_list.yml
@@ -53,19 +53,20 @@ jobs:
 
       - name: Check for Critical Alerts
         run: |
-          # Loop through each generated JSON report
-          for JSON_REPORT in zap-report-*.json; do
-            if [ -f "$JSON_REPORT" ]; then
-              CRITICAL_ALERTS=$(jq '.alerts[] | select(.risk == "High")' "$JSON_REPORT" | wc -l)
-              if [ "$CRITICAL_ALERTS" -gt 0 ]; then
-                echo "Critical alerts found in $JSON_REPORT! Failing the job."
-                exit 1
-              else
-                echo "No critical alerts found in $JSON_REPORT."
-              fi
-            else
-              echo "JSON report $JSON_REPORT not found!"
-            fi
+         for JSON_REPORT in zap-report-*.json; do
+          if [ -f "$JSON_REPORT" ]; then
+          echo "Processing report: $JSON_REPORT"
+          jq '.' "$JSON_REPORT" # Add this line to output the entire report
+          CRITICAL_ALERTS=$(jq '.alerts[] | select(.risk == "High")' "$JSON_REPORT" | wc -l)
+          if [ "$CRITICAL_ALERTS" -gt 0 ]; then
+          echo "Critical alerts found in $JSON_REPORT! Failing the job."
+          exit 1
+          else
+          echo "No critical alerts found in $JSON_REPORT."
+          fi
+          else
+          echo "JSON report $JSON_REPORT not found!"
+          fi
           done
           
       - name: Move ZAP reports to reports directory
